#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking worktrunk configs"

TARGET="${HOME}/.config/worktrunk"
mkdir -p "${TARGET}"
clean_broken_symlinks "${TARGET}"

configs=(
  "config.toml"
)
for config in "${configs[@]}"; do
  mkdir -p "$(dirname "${TARGET}/${config}")"
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
