#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking warp configs"

TARGET="${HOME}/.warp"
mkdir -p "${TARGET}"
clean_broken_symlinks "${TARGET}"

configs=(
  "keybindings.yaml"
)
for config in "${configs[@]}"; do
  mkdir -p "$(dirname "${TARGET}/${config}")"
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done

TARGET="${HOME}/.warp/themes"
mkdir -p "${TARGET}"
clean_broken_symlinks "${TARGET}"

configs=(
  "rootloops.yaml"
)
for config in "${configs[@]}"; do
  mkdir -p "$(dirname "${TARGET}/${config}")"
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
