#!/usr/bin/env bash
cd "$(dirname "$0")"
source ../../scripts/helpers/runtime.sh
source ../../bin/helpers/trap_and_trace.sh

log_info "Symlinking zsh configs"

TARGET="${HOME}"

# https://www.freecodecamp.org/news/how-do-zsh-configuration-files-work/
#
# .zshenv: This is loaded universally for all types of shell sessions (interactive or non-interactive, login or non-login). It is the only configuration file that gets loaded for non-interactive and non-login scripts like cron jobs. However, macOS overrides this for PATH settings for interactive shells.
# .zprofile: Loaded for login shells (both interactive and the rare non-interactive sessions). MacOS uses this to set up the shell for any new terminal window. Subshells that start within the terminal window inherit settings but don't load ~/.zprofile again.
# .zshrc: Loaded only for interactive shell sessions. It is loaded whenever you open a new terminal window or launch a subshell from a terminal window.
# .zlogin: Only used for login shell configurations, loaded after .zprofile. This is loaded whenever you open a new terminal window.
# .zlogout: Only used for login shell configurations. This is loaded whenever a login shell exits.
#
# Use ~/.zprofile to set the PATH and EDITOR environment variables.
# Use ~/.zshrc for aliases and a custom prompt, tweaking the appearance and behavior of the terminal.
configs=(
  ".zshenv"
  ".zprofile"
  ".zshrc"
  ".zlogin"
  ".zlogout"
)
for config in "${configs[@]}"; do
  symlink_config "${PWD}/${config}" "${TARGET}/${config}"
done
