brew_taps:
  - name: 'homebrew/cask'

brew_packages:
  - name: httpie
  - name: jq

  - name: cabal-install
  - name: ghc
  - name: haskell-stack

  - name: mas

  - name: maven
  - name: npm

brew_casks:
  - name: alfred
  - name: docker
  - name: firefox
  - name: macvim
  - name: slack
  - name: sourcetree
